
dictumText = [
    "I allow others to be better than me, but I don't allow me to work without others.",
    "To be honest, to be honest.",
    "You should learn to run hard, and not be ruined by the secular world.",
    "Twist into a rope, strive to do a part of the force, hard next heart, a dream.",
    "Although it's hard to wash thousands of clothes, it's hard to blow all the sand before gold comes.",
    "Lovelorn is not necessarily a bad thing, may be the beginning of the next happiness.",
    "If you are tired, stop, look at the sky and continue your journey.",
    "Frustration is just an episode in life. Maybe it's icing on the cake.",
    "Success and failure don't matter. What matters is that we work hard.",
    "Don't make excuses for your failure!",
    "If you can't get lucky. Then, try to be superior.",
    "We will all experience some tribulations that we have never experienced before, and then grow up.",
    "Time is a sharp knife, which has completed my madness and shattered my dream.",
    "No one can decide you but yourself.",
    "Whoever does not rest will not work.",
    "I'm never afraid of thousands of troops to stop me. I'm just afraid of disarming and surrendering myself.",
    "Fight for a spring, summer, autumn and winter, wish you have no regrets.",
    "No ambition, no life.",
    "Failure is not terrible. What's terrible is that you never try.",
    "There is no abstract truth, the truth is always concrete.",
    "Those who have no doubt about reading must have doubts about teaching, while those who have doubts must have no doubt about it. Only here can they make progress.",
    "In order to illuminate the night sky, the stars stand high in the sky.",
    "Low key, between the choices, there must be gains and losses.",
    "Have a dream, even if it's far away.",
    "Don't be a failure. The best revenge is success.",
    "Try to be good and don't let others look down on you.",
    "Although there is a point in life, but never regret choosing tomorrow.",
    "Life is not only about love and hate, but also loneliness and wine, dreams and life, and persistence.",
    "The past depends on the present to forget, the future depends on the present to work hard, now is the most important.",
    "Greed is the most real poverty, and contentment is the most real wealth.",
    "Only those who are not afraid of death deserve to live.",
    "I don't want to fall behind, so let's be good together.",
    "Life is not to grasp a good hand, but how to play a bad card.",
    "Not afraid of a long way, but afraid of a short mind.",
    "Growth is to let us learn to be strong.",
    "The reason why people can is to believe in can.",
    "Stop chasing the light and let yourself shine.",
    "The secret of success is never changing the purpose.",
    "Life doesn't allow you to be willful, accept the reality and work hard.",
    "Anger blinds our judgment.",
    "Any restriction starts from your heart.",
    "Believe in yourself, better than anyone.",
    "Only a down-to-earth man is willing to leave his footprints.",
    "It's the boss of your own life, how to manage or has the final say.",
    "First become the one you like, then meet someone you don't need to please.",
    "Adversity is the highest institution of learning.",
    "Living in the applause of others is a man who can't stand the test.",
    "Many things are only gradually clear after years of precipitation.",
    "People who can only walk on the concrete floor will never leave deep footprints.",
    "Looking back at the lamp as old, hold hands lightly.",
    "As long as you are good enough, whatever you want will come to you.",
    "In order to be lazy in the future, we must work hard now.",
    "Without saliva and sweat, there will be no tears of success.",
    "Learning knowledge should be good at thinking, thinking and thinking again.",
    "To wait for a rabbit, you have to eat a full meal. Only when you take the initiative can you have enough food and clothing.",
    "Giving up is not the absolute of life.",
    "Reading makes the mind bright.",
    "Victory belongs to those who persist to the end.",
    "Those who can only dream but not act will never feel the joy of harvest.",
    "You want everything if you don't work hard.",
    "What can't be forgotten is memories, and what goes on is life.",
    "A fool thinks he is clever. A wise man knows he is a fool.",
    "A woman can not be born beautiful, but must live beautiful.",
    "Nothing is the reason for combo.",
    "The dream is not big, the road is long, don't stop when you start.",
    "I'm not fragile, what's more!",
    "If you want to be young without regrets, you must dare to do what you want.",
    "Success lies in the exertion of advantages and failure in the accumulation of disadvantages.",
    "Only becoming good can make my soul full.",
    "Hope is the faithful sister of misfortune.",
    "As long as you don't care about gain and loss, there is nothing in life that can't be overcome.",
    "What sustains a person's life is his career.",
    "Books are the tools of the soul.",
    "Opportunity is more important than stability, career is more important than money, and future is more important than today.",
    "I don't believe in the lines of the palm, but I believe in the power of the palm plus the fingers.",
    "Action does not necessarily bring happiness, but without action there is no happiness.",
    "I'm so poor and I don't work hard. What else can I sigh for.",
    "Right, insist; wrong, give up!",
    "Looking forward to the spring belongs to nature, hand woven spring belongs to themselves.",
    "There's nothing to do with it, it's just that someone has set up a day for you.",
    "All your efforts will eventually be rewarded to yourself in a big circle.",
    "Rome wasn't built in a day.",
    "Even if the dream is far away, but as long as we stick to it, there will be a day to realize it.",
    "I hate myself for being unwilling to be ordinary, but I don't work hard.",
    "Man's value is determined by himself.",
    "Thirty years on the East and thirty years on the west, do not deceive the poor.",
    "Work hard. You will have everything you want now.",
    "Human wisdom will wither when it is not used.",
    "A stumbling block is a step forward.",
    "I feel that what I do and what I don't do is only between one thought.",
    "To be strong, to be brave, to be brave through the wind and rain.",
    "Only a wise man can find the answer from the usual details, rather than waiting for the answer.",
    "You must take what you want, or you can't afford it even if someone gives it to you.",
    "We walk all the way, all the way to be disappointed, all the way to ignite hope, all the way to find the answer.",
    "Look at me. Come with me. Do it together.",
    "Wish you can carry your dream and bring the sunshine to the distance.",
    "It is a well-known law of cause and effect that how much you give and how much you get.",
    "Don't think about making the sea. You have to start with small rivers.",
    "Good habits are the guarantee of success.",
    "Man, the greatest enemy is himself.",
    "Winners are not those who never fail, but those who never give up.",
    "We can't choose fate, but we can change it.",
    "Only when you know how to bow your head can you get ahead.",
    "Please try again for the people you want to see and the things you want to do.",
    "The ideal of a hen is nothing but a handful of chaff.",
    "Yesterday, delete, today, strive for, tomorrow, strive for.",
    "As long as you believe, it's possible.",
    "In order to become the ideal self, every day to work hard.",
    "Failure doesn't mean that you are bad, but reminds you that it's time to work hard.",
    "It's the meaning of hard work to keep everything you like.",
    "As long as you don't give up, you have a chance!",
    "The days ahead are brand new. Don't look back.",
    "Thanks to the last second of their own, adhere to create new miracles.",
    "Can，isthatthepeoplecanbelievethat。",
    "Noexcusesforfailure，tofindwaystosuccess。",
    "Indomitablewillpowercanconqueranypeakintheworld！",
    "Letoneselflearneveryday，someprogress。",
    "Putthequestiontoseesomebroad，noproblemtoo。",
    "Togreatcauses，inadditiontodream，mustact。",
    "Holdon，successiswaitingforyouatthenextcorner。",
    "Thelawofsuccessisverysimple，butsimpledoesn'tmeaneasy。",
    "Willedit；Ihavestrength；Hastheperseverance，youwillsucceed！",
    "Learningisnotnecessarilysuccessful，notlearncan'tbecertainofsuccess。",
    "Theonlythingwehaveistoday，theonlyistograsptoday。",
    "Allgreatactionsandthoughts，allhaveainsignificantbeginning。",
    "Believeinyourself，believethatpartner。Grasptheopportunities，easytosuccess。",
    "Causeapositivelife，positivethinkingnegativethoughtsleadnegativelife。",
    "Perfectionofhumancharacteristhe，theestablishmentofthewealthisthelast。",
    "Everysuccessfulpersonhasastart。Startbravelytofindasuccessfulway。",
    "Theso-calledgenius，justwithalltheothersdrinkcoffeetimeonthejob。",
    "Themoreoneknowsthevalueoftime，themorefeelthepainofthelost。",
    "Whenapersonfromhisfirstheartbeginstostruggle，heisamanofvalue。",
    "Ihavetwofaithfulassistant，oneismypatience，anotherismyhands。",
    "Thinkhonestyisthesoulofcultivateone'smorality，andMingisgoodtothinkhonestly。",
    "Ordinarysimpledream，weusedtheonlyadheretothebelieftosupportthedream。",
    "Keepconfident，knowyourvalue，canbeareallydeterminedtheirowntreasure。",
    "Complacencyisaterribletrapour；And，thistrapiswedigmyself。",
    "Fearhardship，bitterforalifetime，doesnotfearendureshardshippeoplebitterforawhile。",
    "Successiswithcourageandhardwork，constantlytranscendyourself，doyourbest。",
    "Anyqualitativetransformationofoutstandingachievementscomesfromquantitativeaccumulation。",
    "Willonlyfantasyandnotamanofaction，neveralsoexperiencethejoyofharvest。",
    "Peoplearealsooftenthetruthanderrortogethertoteach，andinsistoniswrong。",
    "Thesecretofsuccessliesinhowhardagain。Inordertosucceed，howmanytimeshaveyoutried？",
    "Readingisgood，butyouhavetorememberthatbookisabook，however，havetotheirideas。",
    "Optimismisapassionatebeautifulmomentofmarch，inspiringyoutocausetheroadahead。",
    "Aperson，daretolistentothetruth，needcourage；Amandaretotellthetruth，needtodrive。",
    "Iwouldliketoprovethateveryactofkindnessandnobleperson，cansoandbeartheirtroubles。",
    "Stupidpeoplealwaysregretyesterday，toprayfortomorrow，it'sapityeffortsoftoday。",
    "Treateverydreamoflife，confidencetooneself，toknowthatyouhavetheabilitytoachieveit。",
    "Noonecanpredictthefuturedestiny，butwecanusethejoyfulexpressioninthefaceoffate。",
    "Peopleonthewisdomshouldbebrightandclear，moralshouldbeinnocent，bodyshouldbeclean。",
    "Atordinarytimesdidnotrunhairwhokm，accountingforwhenitwillbedifficulttoonehundredmetressprint。",
    "Endureotherpeoplecan'tendurethepain，eatotherpeoplecan'teatbitter，toharvestnotharvest。",
    "Thosewhoareintheprocessoftakefailureasaresult，ratherthan，rarelycanseesignsofsuccess。",
    "Tobegratefulforbad，letoneselfwithasoftheartinclusiveworld。Themostpowerfulsoftheart。",
    "Goodmoodwillhavegoodscenery，goodvisionwillhaveagoodfind，goodthinkingwillhaveagoodidea。",
    "Aroundlikeamagnetattractsironpowder，alsocanattractthepeoplearoundyou，changethesituationaround。",
    "Thereisapeopleonlydotwothings：youaresuccessful，hisjealousofyou；Youhavefailed，helaughatyou。",
    "Againlongway，stepbystep，alsocangothrough，againashortroad，donotstridefeetcan'treach。",
    "Theadultismoreimportantthansuccess，willstudyismoreimportantthantolearn，progressismoreimportantthanlead。",
    "Nomatterwhatthingscan'tbecareless，besuretoputthethingstoconsidercarefullybeforetheydo。",
    "ForthestudyofdiggingWells，themoredifficultthewellthedeepsoil，ifunhappyhearttotheend，ortoseeafountain？",
    "Endureotherpeoplecan'tendurethepain，theotherswhattheycan'teatbitter，toharvestnotharvest。",
    "Knowingthedifficulties，workhard，itistheroleofcompetition；Theboatbutnegative，andtheroleofcompetition。",
    "Moneyisakindofability，moneyisakindoflevel，abilitytopractice，practicenottocomeoutofleveliseasy。",
    "Ifyouforgottenbythegodoffortune，pleasedon'tbesad，believethatthesunwillshineonedayalwaysuponyou。",
    "Theworldwon'tcareaboutyourself-esteem，onlycareaboutyoutomakeachievements，thentoemphasizehowyoufeel。",
    "Forward，makestheboatoflifewithoutattachmentandmooring，sailingboatoftennewflowerswillopenalltheway。",
    "Don'ttoguessthethoughtsofothers，ifyoudon'thavethewisdomandexperienceofcorrectjudgment，therewillbewrong。",
    "Happinesstothepersonbecomfortable，butgiveapersontodeath；Worktohonetotheperson，cangiveapersonforalongtime。",
    "Lifeforsportsandwonderful，forfunandfulloflife，learntothinkforanddeep，makefriendswithsincereandpersistent！",
    "Thankyouforthecomingofthenight，Iknowthatnomatterhowfailuretoday，anewtomorrow，stillwaitingformetoprovehimself",
    "To be both a speaker of words and a doer of deeds.",
    "Variety is the spice of life.",
    "Bad times make a good man.",
    "There is no royal road to learning.",
    "Doubt is the key to knowledge.",
    "The greatest test of courage on earth is to bear defeat without losing heart.",
    "A man's best friends are his ten fingers.",
    "Only they who fulfill their duties in everyday matters will fulfill them on great occasions.",
    "The shortest way to do many things is to only one thing at a time.",
    "Sow nothing, reap nothing.",
    "Life is real, life is earnest.",
    "Life would be too smooth if it had no rubs in it.",
    "Life is the art of drawing sufficient conclusions form insufficient premises.",
    "Life is fine and enjoyable, yet you must learn to enjoy your fine life.",
    "Life is but a hard and tortuous journey.",
    "Life is a horse, and either you ride it or it rides you.",
    "Life is a great big canvas, and you should throw all the paint on it you can.",
    "Life is like music. It must be composed by ear, feeling and instinct, not by rule.",
    "Life is painting a picture, not doing a sum.",
    "The wealth of the mind is the only wealth.",
    "You can't judge a tree by its bark.",
    "Sharp tools make good work.",
    "Wasting time is robbing oneself.",
    "Nurture passes nature.",
    "There is no garden without its weeds.",
    "A man is only as good as what he loves.",
    "Wealth is the test of a man's character.",
    "The best hearts are always the bravest.",
    "One never lose anything by politeness.",
    "There's only one corner of the universe you can be sure of improving, and that's your own self.",
    "The world is like a mirror: Frown at it and it frowns at you; smile, and it smiles too.",
    "Death comes to all, but great achievements raise a monument which shall endure until the sun grows old.",
    "The reason why a great man is great is that he resolves to be a great man.",
    "Suffering is the most powerful teacher of life.",
    "A bosom friend afar brings a distant land near.",
    "A common danger causes common action.",
    "A contented mind is a continual / perpetual feast.",
    "A fall into the pit, a gain in your wit.",
    "A guest should suit the convenience of the host.",
    "A letter from home is a priceless treasure.",
    "All rivers run into the sea.",
    "All time is no time when it is past.",
    "An apple a day keeps the doctor away.",
    "As heroes think, so thought Bruce.",
    "A young idler, an old beggar.",
    "Behind the mountains there are people to be found.",
    "Bad luck often brings good luck.",
    "Business is business.",
    "Clumsy birds have to start flying early.",
    "Do one thing at a time, and do well.",
    "Custom makes all things easy.",
    "Desire has no rest.",
    "Difficult the first time, easy the second.",
    "Do not change horses in mid-stream.",
    "Do not have too many irons in the fire.",
    "Do not teach fish to swim.",
    "East or west, home is the best.",
    "Experience is the best teacher.",
    "Faith can move mountains.",
    "First impressions are half the battle.",
    "Good wine needs no bush.",
    "Haste makes waste.",
    "He that promises too much means nothing.",
    "He who has an art has everywhere a part.",
    "He would climb the ladder must begin at the bottom.",
    "Home is where the heart is.",
    "If you are not inside a house, you don not know about its leaking.",
    "It is never too late to mend.",
    "It six of one and half a dozen of the other.",
    "Just has long arms.",
    "Keep something for a rainy day.",
    "Life is a span.",
    "Man proposes, God disposes.",
    "Meet plot with plot.",
    "Merry meet, merry part.",
    "Mind acts upon mind.",
    "Never hit a man when he is down.",
    "Never judge by appearances.",
    "No fire without smoke.",
    "Nurture passes nature.",
    "One is never too old to learn.",
    "One swallow does not make a summer.",
    "One who has seen the ocean thinks nothing of mere rivers.",
    "Out of sight, out of mind.",
    "Practice makes perfect.",
    "Poverty is stranger to industry.",
    "Rome was not built in a day.",
    "Sense comes with age.",
    "So many men, so many minds.",
    "Some thing is learned every time a book is opened.",
    "Strike while the iron is hot.",
    "The car will find its way round the hill when it gets there.",
    "The heart is seen in wine.",
    "The worse luck now, the better another time.",
    "Time tries all things.",
    "Use legs and have legs.",
    "Virtue never grows old.",
    "Walls have ears.",
    "What is done cannot be undone.",
    "Wine in, truth out.",
]